name: logging_handlers
version: 0.5.0+1
author: Chris Buckett <chrisbuckett@gmail.com>
description: A selection of handlers that you can use as targets for the "logger" pub package
environment:
  sdk: '>=0.5.0+1.r21823'
dependencies:
  intl: 0.5.0+1
  web_ui: 0.4.6+2
  logging: 0.5.0+1
dev_dependencies:
  unittest: 0.5.0+1
  browser: '>=0.5.0+1'

#dependencies:
#  unittest: any