name: logging_handlers
version: 0.5.13
author: Chris Buckett <chrisbuckett@gmail.com>
description: A selection of handlers that you can use as targets for the "logger" pub package.  Stop using print() and start using logger.info()
homepage: https://github.com/chrisbu/logging_handlers
environment:
  sdk: '>=0.5.13+1'
dependencies:
  intl: 0.5.13
  logging: 0.5.13
  web_ui: 0.4.9+5
dev_dependencies:
  browser: 0.5.13
  unittest: 0.5.13

#dependencies:
#  unittest: any