name: logging_handlers
version: 0.5.0+1
author: Chris Buckett <chrisbuckett@gmail.com>
description: A selection of handlers that you can use as targets for the "logger" pub package.  Stop using print() and start using logger.info()
homepage: https://github.com/chrisbu/logging_handlers
environment:
  sdk: '>=0.8.7'
dependencies:
  intl: '>=0.8.7'
  web_ui: '>=0.4.23'
  logging: '>=0.8.7'
dev_dependencies:
  unittest: '>=0.8.7'
  browser: '>=0.8.7'

#dependencies:
#  unittest: any