name: logging_handlers
version: 0.5.0+2
author: Chris Buckett <chrisbuckett@gmail.com>
description: A selection of handlers that you can use as targets for the "logger" pub package
environment:
  sdk: '>=0.5.0+1.r21823'
dependencies:
  intl: any
  web_ui: any
  logging: any
dev_dependencies:
  unittest: any
  browser: any

#dependencies:
#  unittest: any