// Auto-generated from test.html.
// DO NOT EDIT.

library test_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import '_from_packages/logging_handlers/src/client/loggerui.dart';
import 'dart:html';
import 'package:logging_handlers/browser_logging_handlers.dart';
import 'package:logging/logging.dart';
import 'dart:async';


// Original code
 

main() {
   hierarchicalLoggingEnabled = true;
   Logger.root.level = Level.OFF;
   var logger = new Logger("mylogger")..level = Level.ALL;
   new Logger("loggerui");//..level = Level.ALL;
   
   
   attachXLoggerUi();
   
   
   query("#click").onClick.listen((_) {
     logger.info("Button clicked");
     debug("Foo", "loggerui");
   });
   
 }
// Additional generated code
void init_autogenerated() {
  var _root = autogenerated.document.body;
  var __e0;
  var __t = new autogenerated.Template(_root);
  __e0 = _root.nodes[3];
  __t.component(new LoggerUi()..host = __e0);
  __t.create();
  __t.insert();
}

//@ sourceMappingURL=test.dart.map